# SITE CONFIGURATION
title: NgopiBrek! # your site title
author: NgopiBrek # You :P
description: > # Meta description of Homepage
  NgopiBrek adalah sebutan dari ngopi sambil ngoprek, melakukan aktivitas ngoding sambil berlajar dari berbagai repo github.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ngopibrek.wildanfauzy.com" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: NgopiBrek!
  links:
    - https://twitter.com/NgopiBrek
    - https://github.com/NgopiBrek

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Ngopi Sambil Ngoprek

hero_img: posts/tentang.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: admin@wildanfauzy.com # email for form submission

twitter_username: NgopiBrek # replace with your_twitter_username or comment to remove link from footer
github_username:  NgopiBrek # replace with your_github_username or comment to remove link from footer
instagram_username: NgopiBrek # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: wildanfauzy # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
